-- Supabase 数据库初始化脚本
-- 在 Supabase 后台的 SQL Editor 中运行此脚本

-- 创建 brand_data 表
CREATE TABLE IF NOT EXISTS brand_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    data JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建 bacashi_data 表
CREATE TABLE IF NOT EXISTS bacashi_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    data JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_brand_data_key ON brand_data(key);
CREATE INDEX IF NOT EXISTS idx_bacashi_data_key ON bacashi_data(key);

-- 插入初始数据（可选）
INSERT INTO brand_data (key, data)
VALUES ('main', '{"brand":{"description":"卡斐乐是一家专注于高品质产品研发与制造的企业","stats":{"years":15,"products":10000,"customers":100000000}},"contact":{"address":"浙江省义乌市北苑街道秋实路 121 号 2 号楼 8 楼","phone":"400-888-8888","email":"info@cafele.com"},"timeline":[],"products":[]}')
ON CONFLICT (key) DO NOTHING;

INSERT INTO bacashi_data (key, data)
VALUES ('main', '{"brand":{"description":"倍卡西是一家专注于高品质产品研发与制造的企业","stats":{"years":2,"products":80,"customers":3000}},"contact":{"address":"浙江省义乌市北苑街道秋实路 121 号 2 号楼 8 楼","phone":"400-666-6666","email":"contact@bacashi.com"},"timeline":[],"products":[]}')
ON CONFLICT (key) DO NOTHING;
